"""empty message

Revision ID: aea311e55897
Revises: 
Create Date: 2020-02-12 15:56:45.752989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aea311e55897'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reminder',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('image_file', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('car',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('fuel', sa.String(length=100), nullable=False),
    sa.Column('matriculation', sa.DateTime(), nullable=False),
    sa.Column('image_file', sa.String(length=20), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('car_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataInt', sa.Integer(), nullable=True),
    sa.Column('dataDate', sa.DateTime(), nullable=True),
    sa.Column('carDataCode', sa.Integer(), nullable=False),
    sa.Column('id_car', sa.Integer(), nullable=False),
    sa.Column('id_reminder', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_car'], ['car.id'], ),
    sa.ForeignKeyConstraint(['id_reminder'], ['reminder.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('car_data')
    op.drop_table('car')
    op.drop_table('user')
    op.drop_table('reminder')
    # ### end Alembic commands ###
